### PR TITLE
changed the manual Installation part of the readme

### PR DESCRIPTION
**Pull request by Rexcrazy804**
changed the first 2 steps of the manual installation, simplifying the installation

### CODE REVIEW

**Review by sts10 — CHANGES_REQUESTED** [review]
Thanks for the PR! 

I like the idea of simplifying the installation process like this, but I think the `>>` command _appends_ the first command's output to the file, which in this case could create some issues. I think the better choice would be to overwrite with `>`. 

Though personally I'm more familiar/comfortable using `curl`'s `o` flag (and it's [what this popular jellybeans repo](https://github.com/nanotech/jellybeans.vim#installation) uses):
 
`curl -o ~/.vim/colors/pink-moon.vim https://raw.githubusercontent.com/sts10/vim-pink-moon/master/colors/pink-moon.vim`

**Comment by Rexcrazy804** [comment]
I was unaware of that flag, will rework it right away.

**Comment by sts10** [comment]
A little different than I would have done, but I like that your solution works for users that don't yet have `~/.vim` directory (though I'm not sure how'd they have Vim installed and not have that directory created, but I'm fine being safe).

**Comment by Rexcrazy804** [comment]
It was my first time installing color schemes for vim and I hadn't the vim/colors folder. It hit me when i went through the jellybean repo you suggested. Glad you like it :)

(Its my first ever commit and I am super happy to have it merged to master >w<)

**Pull request merged**
